export const TIC_TAC_TOE_PREFIX = '@@tic-tac-toe';
export const RESET_GAME = `${TIC_TAC_TOE_PREFIX}:RESET_GAME`;
export const FILL_SQUARE = `${TIC_TAC_TOE_PREFIX}:FILL_SQUARE`;
export const JOIN_GAME = `${TIC_TAC_TOE_PREFIX}:JOIN_GAME`;
export const JOIN_ROOM = `${TIC_TAC_TOE_PREFIX}:JOIN_ROOM`;
export const SYNC_GAME_STATE = `${TIC_TAC_TOE_PREFIX}:SYNC_GAME_STATE`;
